# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from figurative_server import FigurativeServer_pb2 as figurative__server_dot_FigurativeServer__pb2


class FigurativeServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartNative = channel.unary_unary(
                '/figurative_server.FigurativeServer/StartNative',
                request_serializer=figurative__server_dot_FigurativeServer__pb2.NativeArguments.SerializeToString,
                response_deserializer=figurative__server_dot_FigurativeServer__pb2.FigurativeInstance.FromString,
                )
        self.StartEVM = channel.unary_unary(
                '/figurative_server.FigurativeServer/StartEVM',
                request_serializer=figurative__server_dot_FigurativeServer__pb2.EVMArguments.SerializeToString,
                response_deserializer=figurative__server_dot_FigurativeServer__pb2.FigurativeInstance.FromString,
                )
        self.Terminate = channel.unary_unary(
                '/figurative_server.FigurativeServer/Terminate',
                request_serializer=figurative__server_dot_FigurativeServer__pb2.FigurativeInstance.SerializeToString,
                response_deserializer=figurative__server_dot_FigurativeServer__pb2.TerminateResponse.FromString,
                )
        self.GetStateList = channel.unary_unary(
                '/figurative_server.FigurativeServer/GetStateList',
                request_serializer=figurative__server_dot_FigurativeServer__pb2.FigurativeInstance.SerializeToString,
                response_deserializer=figurative__server_dot_FigurativeServer__pb2.FigurativeStateList.FromString,
                )
        self.GetMessageList = channel.unary_unary(
                '/figurative_server.FigurativeServer/GetMessageList',
                request_serializer=figurative__server_dot_FigurativeServer__pb2.FigurativeInstance.SerializeToString,
                response_deserializer=figurative__server_dot_FigurativeServer__pb2.FigurativeMessageList.FromString,
                )
        self.CheckFigurativeRunning = channel.unary_unary(
                '/figurative_server.FigurativeServer/CheckFigurativeRunning',
                request_serializer=figurative__server_dot_FigurativeServer__pb2.FigurativeInstance.SerializeToString,
                response_deserializer=figurative__server_dot_FigurativeServer__pb2.FigurativeRunningStatus.FromString,
                )
        self.StopServer = channel.unary_unary(
                '/figurative_server.FigurativeServer/StopServer',
                request_serializer=figurative__server_dot_FigurativeServer__pb2.StopServerRequest.SerializeToString,
                response_deserializer=figurative__server_dot_FigurativeServer__pb2.StopServerResponse.FromString,
                )
        self.ControlState = channel.unary_unary(
                '/figurative_server.FigurativeServer/ControlState',
                request_serializer=figurative__server_dot_FigurativeServer__pb2.ControlStateRequest.SerializeToString,
                response_deserializer=figurative__server_dot_FigurativeServer__pb2.ControlStateResponse.FromString,
                )


class FigurativeServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartNative(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartEVM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Terminate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStateList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessageList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckFigurativeRunning(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FigurativeServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartNative': grpc.unary_unary_rpc_method_handler(
                    servicer.StartNative,
                    request_deserializer=figurative__server_dot_FigurativeServer__pb2.NativeArguments.FromString,
                    response_serializer=figurative__server_dot_FigurativeServer__pb2.FigurativeInstance.SerializeToString,
            ),
            'StartEVM': grpc.unary_unary_rpc_method_handler(
                    servicer.StartEVM,
                    request_deserializer=figurative__server_dot_FigurativeServer__pb2.EVMArguments.FromString,
                    response_serializer=figurative__server_dot_FigurativeServer__pb2.FigurativeInstance.SerializeToString,
            ),
            'Terminate': grpc.unary_unary_rpc_method_handler(
                    servicer.Terminate,
                    request_deserializer=figurative__server_dot_FigurativeServer__pb2.FigurativeInstance.FromString,
                    response_serializer=figurative__server_dot_FigurativeServer__pb2.TerminateResponse.SerializeToString,
            ),
            'GetStateList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStateList,
                    request_deserializer=figurative__server_dot_FigurativeServer__pb2.FigurativeInstance.FromString,
                    response_serializer=figurative__server_dot_FigurativeServer__pb2.FigurativeStateList.SerializeToString,
            ),
            'GetMessageList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessageList,
                    request_deserializer=figurative__server_dot_FigurativeServer__pb2.FigurativeInstance.FromString,
                    response_serializer=figurative__server_dot_FigurativeServer__pb2.FigurativeMessageList.SerializeToString,
            ),
            'CheckFigurativeRunning': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckFigurativeRunning,
                    request_deserializer=figurative__server_dot_FigurativeServer__pb2.FigurativeInstance.FromString,
                    response_serializer=figurative__server_dot_FigurativeServer__pb2.FigurativeRunningStatus.SerializeToString,
            ),
            'StopServer': grpc.unary_unary_rpc_method_handler(
                    servicer.StopServer,
                    request_deserializer=figurative__server_dot_FigurativeServer__pb2.StopServerRequest.FromString,
                    response_serializer=figurative__server_dot_FigurativeServer__pb2.StopServerResponse.SerializeToString,
            ),
            'ControlState': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlState,
                    request_deserializer=figurative__server_dot_FigurativeServer__pb2.ControlStateRequest.FromString,
                    response_serializer=figurative__server_dot_FigurativeServer__pb2.ControlStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'figurative_server.FigurativeServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FigurativeServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartNative(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/figurative_server.FigurativeServer/StartNative',
            figurative__server_dot_FigurativeServer__pb2.NativeArguments.SerializeToString,
            figurative__server_dot_FigurativeServer__pb2.FigurativeInstance.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartEVM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/figurative_server.FigurativeServer/StartEVM',
            figurative__server_dot_FigurativeServer__pb2.EVMArguments.SerializeToString,
            figurative__server_dot_FigurativeServer__pb2.FigurativeInstance.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Terminate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/figurative_server.FigurativeServer/Terminate',
            figurative__server_dot_FigurativeServer__pb2.FigurativeInstance.SerializeToString,
            figurative__server_dot_FigurativeServer__pb2.TerminateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStateList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/figurative_server.FigurativeServer/GetStateList',
            figurative__server_dot_FigurativeServer__pb2.FigurativeInstance.SerializeToString,
            figurative__server_dot_FigurativeServer__pb2.FigurativeStateList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMessageList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/figurative_server.FigurativeServer/GetMessageList',
            figurative__server_dot_FigurativeServer__pb2.FigurativeInstance.SerializeToString,
            figurative__server_dot_FigurativeServer__pb2.FigurativeMessageList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckFigurativeRunning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/figurative_server.FigurativeServer/CheckFigurativeRunning',
            figurative__server_dot_FigurativeServer__pb2.FigurativeInstance.SerializeToString,
            figurative__server_dot_FigurativeServer__pb2.FigurativeRunningStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/figurative_server.FigurativeServer/StopServer',
            figurative__server_dot_FigurativeServer__pb2.StopServerRequest.SerializeToString,
            figurative__server_dot_FigurativeServer__pb2.StopServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ControlState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/figurative_server.FigurativeServer/ControlState',
            figurative__server_dot_FigurativeServer__pb2.ControlStateRequest.SerializeToString,
            figurative__server_dot_FigurativeServer__pb2.ControlStateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
